### ISSUE TITLE
regex error in handle_comment

### ISSUE THREAD

**Issue by vtjnash** [JuliaWeb/GitHub.jl#188] opened 2021-08-24 18:49 UTC
At https://github.com/JuliaWeb/GitHub.jl/blob/937c0b59915fff925fef374584f7e116bddea3f0/src/activity/events.jl#L194, "body" is assumed to be valid, but in logs, it seems like this may be `nothing` instead: https://github.com/JuliaCI/Nanosoldier.jl/issues/95

**Comment by rick2047** [comment] 2021-11-02 14:07
How would we solve this. Just parse it as empty?

**Comment by vtjnash** [comment] 2021-11-02 14:19
Sure, that probably would be fine, or add an early exit

**Comment by rick2047** [comment] 2021-11-02 14:39
There is also 
https://github.com/JuliaWeb/GitHub.jl/blob/937c0b59915fff925fef374584f7e116bddea3f0/src/activity/events.jl#L196 
Which seems to be the intended behaviour when match is empty

**Comment by fredrikekre** [comment] 2021-11-02 14:42
Probably just updating to
```
trigger_match = match(trigger, get(body_container, "body", nothing))
```
is fine the.

**Comment by rick2047** [comment] 2021-11-02 15:13
The body field exists though, there is just a `nothing` in it.

**Comment by vtjnash** [comment] 2021-11-02 15:41
https://docs.github.com/en/rest/reference/issues#comments

> Update an issue
![image](https://user-images.githubusercontent.com/330950/139879599-47b38164-1fff-4bab-9b43-68ba8568b385.png)

Looks like updating a PR (e.g. changing the title, state, etc.) might not include the body field?

**Comment by fredrikekre** [comment] 2021-11-02 15:52
Perhaps
```
trigger_match = match(trigger, something(get(body_container, "body", nothing), ""))
```
then

**Comment by maleadt** [comment] 2022-11-24 09:56
Fixed by https://github.com/JuliaWeb/GitHub.jl/pull/197

**Closed by maleadt** 2022-11-24 09:56 UTC
